export { default as ProfilePage } from "./profile-page/profile-page"
export { default as SignUpPage } from "./sign-up/sign-up"
export { default as SignInPage } from "./sign-in/sign-in"
export { NotFoundPage } from "./404/404"
export { ServerErrorPage } from "./500/500"
export { default as ChatPage } from "./chat/chat"
export { Page, getBlockByPage } from "./pages"
